[workspace]
channels = ["conda-forge"]
name = "labcamstreamer"
platforms = ["win-64", "osx-64", "osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
flask = ">=3.1.2,<4"
numpy = ">=2.3.3,<3"
opencv = ">=4.12.0,<5"
matplotlib = ">=3.10.6,<4"
scipy = ">=1.15.0,<2"
pillow = ">=11.0.0,<12"
debugpy = ">=1.8.0,<2"

[pypi-dependencies]
pytest = ">=8.3.3,<9"

[target.win-64.pypi-dependencies]
# Allied Vision supplies wheels only for Windows; other platforms fall back to FakeCamera.
vmbpy = ">=1.1.1,<2"
